from ..loggers import LOG_FILE_PATH
from ._config_history import ConfigIdentity, FieldValueWithKey
from ._overload_history import (
    PatchConfigHistory,
    preventive_missing_warning,
    reinitiate_config,
    validate_configuration,
)
from .config import (
    APP_BRAND_NAME,
    APP_DATA_DIR,
    APP_NAME,
    CONFIG_FILE_EXTENSION,
    CONFIG_FILE_NAME,
    DEFAULT_EXPORT_DATA_FORMAT,
    DEVELOPMENT_MODE,
    EXTERNAL_LOCAL_PLUGIN_DIR,
    EXTERNAL_LOCAL_PLUGIN_DIRECTORY_NAME,
    EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_CLI_SCRIPT_PATH,
    EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_FILE_EXISTS,
    EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_PLUGIN_NAME,
    EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_PROJECT_PATH,
    EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_VENV_PATH,
    EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME,
    EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME_PREFIX,
    EXTERNAL_LOCAL_PLUGIN_METADATA_KEY_PLUGIN_ROOT_DIR,
    EXTERNAL_LOCAL_PLUGIN_TYPER_APP_FILE_NAME,
    EXTERNAL_LOCAL_PLUGIN_TYPER_APP_VAR_NAME,
    FALLBACK_EXPORT_DIR,
    FALLBACK_SOURCE_NAME,
    KEY_DEVELOPMENT_MODE,
    KEY_PLUGIN_KEY_NAME,
    LOCAL_CONFIG_LOC,
    NON_CANON_YAML_EXTENSION,
    PLUGIN,
    PROJECT_CONFIG_LOC,
    SYSTEM_CONFIG_LOC,
    VERSION_FILE_NAME,
    MinimalConfigData,
    history,
    inspect,
    minimal_active_configuration,
    settings,
)
from .overridable_vars import (
    get_plugin_configs,
    get_development_mode,
)
from .validators import ConfigurationValidation
from .validators import PluginConfigurationValidator as _PluginConfigurationValidator

if get_development_mode(skip_validation=True) is False:
    validate_configuration(limited_to=[_PluginConfigurationValidator])


__all__ = [
    "LOG_FILE_PATH",
    "ConfigIdentity",
    "FieldValueWithKey",
    "PatchConfigHistory",
    "preventive_missing_warning",
    "reinitiate_config",
    "validate_configuration",
    "APP_BRAND_NAME",
    "APP_DATA_DIR",
    "APP_NAME",
    "NON_CANON_YAML_EXTENSION",
    "CONFIG_FILE_EXTENSION",
    "CONFIG_FILE_NAME",
    "DEFAULT_EXPORT_DATA_FORMAT",
    "DEVELOPMENT_MODE",
    "EXTERNAL_LOCAL_PLUGIN_DIR",
    "EXTERNAL_LOCAL_PLUGIN_DIRECTORY_NAME",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_CLI_SCRIPT_PATH",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_FILE_EXISTS",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_PLUGIN_NAME",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_PROJECT_PATH",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_VENV_PATH",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME_PREFIX",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_KEY_PLUGIN_ROOT_DIR",
    "EXTERNAL_LOCAL_PLUGIN_TYPER_APP_FILE_NAME",
    "EXTERNAL_LOCAL_PLUGIN_TYPER_APP_VAR_NAME",
    "FALLBACK_EXPORT_DIR",
    "FALLBACK_SOURCE_NAME",
    "KEY_DEVELOPMENT_MODE",
    "KEY_PLUGIN_KEY_NAME",
    "LOCAL_CONFIG_LOC",
    "PLUGIN",
    "PROJECT_CONFIG_LOC",
    "SYSTEM_CONFIG_LOC",
    "VERSION_FILE_NAME",
    "MinimalConfigData",
    "history",
    "inspect",
    "settings",
    "minimal_active_configuration",
    "get_plugin_configs",
    "get_development_mode",
    "ConfigurationValidation",
]
