from pathlib import Path

from properpath import P

from .._names import (
    APP_BRAND_NAME,
    APP_NAME,
    CONFIG_FILE_EXTENSION,
    CONFIG_FILE_NAME,
    DEFAULT_EXPORT_DATA_FORMAT,
    KEY_DEVELOPMENT_MODE,
    KEY_PLUGIN_KEY_NAME,
    VERSION_FILE_NAME,
    app_dirs,
)

__all__ = [
    "APP_BRAND_NAME",
    "APP_NAME",
    "CONFIG_FILE_EXTENSION",
    "CONFIG_FILE_NAME",
    "DEFAULT_EXPORT_DATA_FORMAT",
    "KEY_DEVELOPMENT_MODE",
    "KEY_PLUGIN_KEY_NAME",
    "VERSION_FILE_NAME",
    "EXTERNAL_LOCAL_PLUGIN_DIR",
    "EXTERNAL_LOCAL_PLUGIN_DIRECTORY_NAME",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_CLI_SCRIPT_PATH",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_FILE_EXISTS",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_PLUGIN_NAME",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_PROJECT_PATH",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_VENV_PATH",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME_PREFIX",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_KEY_PLUGIN_ROOT_DIR",
    "EXTERNAL_LOCAL_PLUGIN_TYPER_APP_FILE_NAME",
    "EXTERNAL_LOCAL_PLUGIN_TYPER_APP_VAR_NAME",
    "EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_EXT",
    "INTERNAL_PLUGIN_DIRECTORY_NAME",
    "INTERNAL_PLUGIN_TYPER_APP_FILE_NAME",
    "INTERNAL_PLUGIN_TYPER_APP_VAR_NAME",
    "ROOT_INSTALLATION_DIR",
]


# Plugin file definitions and locations
ROOT_INSTALLATION_DIR: Path = Path(__file__).parent.parent
INTERNAL_PLUGIN_DIRECTORY_NAME: str = KEY_PLUGIN_KEY_NAME.lower()
INTERNAL_PLUGIN_TYPER_APP_FILE_NAME_PREFIX: str = "cli"
INTERNAL_PLUGIN_TYPER_APP_FILE_NAME: str = (
    f"{INTERNAL_PLUGIN_TYPER_APP_FILE_NAME_PREFIX}.py"
)
INTERNAL_PLUGIN_TYPER_APP_VAR_NAME: str = "app"
# Local external/3rd-party plugin definitions
EXTERNAL_LOCAL_PLUGIN_DIRECTORY_NAME: str = INTERNAL_PLUGIN_DIRECTORY_NAME
EXTERNAL_LOCAL_PLUGIN_DIR: P = (
    app_dirs.user_data_dir / EXTERNAL_LOCAL_PLUGIN_DIRECTORY_NAME
)
EXTERNAL_LOCAL_PLUGIN_TYPER_APP_FILE_NAME_PREFIX: str = (
    INTERNAL_PLUGIN_TYPER_APP_FILE_NAME_PREFIX
)
EXTERNAL_LOCAL_PLUGIN_TYPER_APP_FILE_NAME: str = INTERNAL_PLUGIN_TYPER_APP_FILE_NAME
EXTERNAL_LOCAL_PLUGIN_TYPER_APP_VAR_NAME: str = INTERNAL_PLUGIN_TYPER_APP_VAR_NAME
EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME_PREFIX: str = "plugin_metadata"
EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_EXT: str = "toml"
EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME: str = (
    f"{EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME_PREFIX}."
    f"{EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_EXT}"
)

EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_FILE_EXISTS = (
    f"{EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_NAME_PREFIX}_exists"
)
EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_PLUGIN_NAME: str = "plugin_name"
EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_CLI_SCRIPT_PATH: str = "cli_script"
EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_VENV_PATH: str = "venv_dir"
EXTERNAL_LOCAL_PLUGIN_METADATA_FILE_KEY_PROJECT_PATH: str = "project_dir"
EXTERNAL_LOCAL_PLUGIN_METADATA_KEY_PLUGIN_ROOT_DIR: str = "plugin_root_dir"
